*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 13 13:34:53 2023] ***
compiled with version: 8.3.0 on 13 March 2023 13:32:04
os: Linux-3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023
nodename: c7c059f200ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/hoon/whereto
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/hoon/whereto/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon/whereto/django.sock fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.0 (default, Nov 23 2019, 05:36:56)  [GCC 8.3.0]
Python main interpreter initialized at 0x558d1b7a0620
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x558d1b7a0620 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 10.1.1.1 () {48 vars in 948 bytes} [Mon Mar 13 13:37:25 2023] GET / => generated 5797 bytes in 158 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 2/2] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:39:54 2023] GET / => generated 5797 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 3/3] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:39:55 2023] GET / => generated 5797 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 4/4] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:39:55 2023] GET / => generated 5797 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 5/5] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:39:56 2023] GET / => generated 5797 bytes in 2 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 6/6] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:39:56 2023] GET / => generated 5797 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 7/7] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:57:31 2023] GET / => generated 5797 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 8/8] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 13:57:32 2023] GET / => generated 5797 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 9/9] 10.1.1.1 () {44 vars in 882 bytes} [Mon Mar 13 13:57:46 2023] GET /story/index/ => generated 3481 bytes in 147 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 10/10] 10.1.1.1 () {44 vars in 908 bytes} [Mon Mar 13 13:57:48 2023] GET /story/index/create/ => generated 3729 bytes in 102 msecs (HTTP/1.1 200) 8 headers in 358 bytes (1 switches on core 0)
Internal Server Error: /story/index/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xEC\\x9C\\xA0\\xED\\x8A\\x9C...' for column `devdb`.`story_book`.`site_con` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 548, in save
    self.instance.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xEC\\x9C\\xA0\\xED\\x8A\\x9C...' for column `devdb`.`story_book`.`site_con` at row 1")
[pid: 7|app: 0|req: 11/11] 10.1.1.1 () {52 vars in 1167 bytes} [Mon Mar 13 13:58:29 2023] POST /story/index/create/ => generated 185194 bytes in 461 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
Internal Server Error: /story/index/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1366, "Incorrect string value: '\\xEB\\x8B\\xA4\\xEC\\x9A\\xB4...' for column `devdb`.`story_book`.`site_cover` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
  File "/usr/local/lib/python3.8/site-packages/django/forms/models.py", line 548, in save
    self.instance.save()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xEB\\x8B\\xA4\\xEC\\x9A\\xB4...' for column `devdb`.`story_book`.`site_cover` at row 1")
[pid: 7|app: 0|req: 12/12] 10.1.1.1 () {52 vars in 1167 bytes} [Mon Mar 13 13:58:51 2023] POST /story/index/create/ => generated 184303 bytes in 173 msecs (HTTP/1.1 500) 7 headers in 243 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 13/13] 10.1.1.1 () {52 vars in 1167 bytes} [Mon Mar 13 14:00:28 2023] POST /story/index/create/ => generated 0 bytes in 32 msecs (HTTP/1.1 302) 7 headers in 233 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 14/14] 10.1.1.1 () {46 vars in 932 bytes} [Mon Mar 13 14:00:28 2023] GET /story/index/ => generated 4818 bytes in 23 msecs (HTTP/1.1 200) 8 headers in 358 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 15/15] 10.1.1.1 () {44 vars in 892 bytes} [Mon Mar 13 14:01:27 2023] GET /main/index/ => generated 5797 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 16/16] 10.1.1.1 () {46 vars in 923 bytes} [Mon Mar 13 14:12:14 2023] GET /main/index/ => generated 5797 bytes in 4 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 17/17] 10.1.1.1 () {46 vars in 923 bytes} [Mon Mar 13 14:12:14 2023] GET /main/index/ => generated 5797 bytes in 3 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 18/18] 10.1.1.1 () {44 vars in 893 bytes} [Mon Mar 13 14:12:16 2023] GET /story/index/ => generated 4818 bytes in 37 msecs (HTTP/1.1 200) 8 headers in 358 bytes (1 switches on core 0)
...brutally killing workers...
*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 13 16:11:28 2023] ***
compiled with version: 8.3.0 on 13 March 2023 13:32:04
os: Linux-3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023
nodename: c7c059f200ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/hoon/whereto
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/hoon/whereto/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon/whereto/django.sock fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.0 (default, Nov 23 2019, 05:36:56)  [GCC 8.3.0]
Python main interpreter initialized at 0x5633595ed620
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5633595ed620 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
...brutally killing workers...
*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 13 16:28:07 2023] ***
compiled with version: 8.3.0 on 13 March 2023 13:32:04
os: Linux-3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023
nodename: c7c059f200ce
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/hoon/whereto
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/hoon/whereto/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /home/hoon/whereto/django.sock fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.0 (default, Nov 23 2019, 05:36:56)  [GCC 8.3.0]
Python main interpreter initialized at 0x563071b5d5f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x563071b5d5f0 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 9, cores: 1)
*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 13 16:28:16 2023] ***
compiled with version: 8.3.0 on 13 March 2023 13:32:04
os: Linux-3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023
nodename: 1bd87c28d88d
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/hoon/whereto
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/hoon/whereto/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/hoon/whereto/django.sock fd 6
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.0 (default, Nov 23 2019, 05:36:56)  [GCC 8.3.0]
Python main interpreter initialized at 0x556037874620
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556037874620 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 1)
[pid: 7|app: 0|req: 1/1] 10.1.1.1 () {44 vars in 855 bytes} [Mon Mar 13 16:30:30 2023] GET / => generated 5797 bytes in 107 msecs (HTTP/1.1 200) 6 headers in 208 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 7|app: 0|req: 2/2] 10.1.1.1 () {42 vars in 774 bytes} [Mon Mar 13 16:30:31 2023] GET /favicon.ico => generated 2543 bytes in 18 msecs (HTTP/1.1 404) 6 headers in 215 bytes (1 switches on core 0)
[pid: 7|app: 0|req: 3/3] 10.1.1.1 () {44 vars in 882 bytes} [Mon Mar 13 16:30:35 2023] GET /story/index/ => generated 4818 bytes in 93 msecs (HTTP/1.1 200) 8 headers in 358 bytes (1 switches on core 0)
